"""empty message

Revision ID: b110b3c64db2
Revises: 
Create Date: 2020-12-22 11:56:55.927021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b110b3c64db2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('soutenances',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('doctorant', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cadeaux',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('auteur', sa.String(length=64), nullable=True),
    sa.Column('idee', sa.String(length=128), nullable=True),
    sa.Column('soutenance_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['soutenance_id'], ['soutenances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('donateur', sa.String(length=64), nullable=True),
    sa.Column('don', sa.Float(), nullable=True),
    sa.Column('is_settled', sa.Boolean(), nullable=True),
    sa.Column('soutenance_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['soutenance_id'], ['soutenances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donations')
    op.drop_table('cadeaux')
    op.drop_table('soutenances')
    op.drop_table('admins')
    # ### end Alembic commands ###
